/// Dining tables use names like "Table 1". Any other name is treated as take-away.
bool isTakeAwayOrderName(String name) => !name.contains('Table');

bool isDiningTableName(String name) => name.contains('Table');

final RegExp _autoTakeAwayNamePattern = RegExp(
  r'^Take\s+Away\s+\d+$',
  caseSensitive: false,
);

bool isAutoGeneratedTakeAwayName(String name) =>
    _autoTakeAwayNamePattern.hasMatch(name.trim());
